// Construit une URL Wikimedia Commons via Special:FilePath.
// Le repli « initiale dorée » est géré par le composant <WikiImage>.
const BASE = 'https://commons.wikimedia.org/wiki/Special:FilePath/';

export function wiki(file: string, width = 500): string {
  if (!file) return '';
  // Le nom peut déjà être encodé ; on ré-encode proprement les espaces.
  const encoded = encodeURIComponent(file).replace(/%2F/g, '/');
  return `${BASE}${encoded}?width=${width}`;
}

// Crédit / licence par fichier (Wikimedia Commons). Affiché en pied de fiche.
export interface Credit {
  auteur: string;
  licence: string;
}

export const CREDITS: Record<string, Credit> = {
  'Pierre Mignard - Portrait de Jean-Baptiste Poquelin dit Molière (1622-1673) - Google Art Project.jpg':
    { auteur: 'Pierre Mignard (Google Art Project)', licence: 'Domaine public' },
  'Shakespeare.jpg': { auteur: 'Attribué à John Taylor', licence: 'Domaine public' },
  'Jean racine.jpg': { auteur: "Atelier de Jean-Baptiste Santerre", licence: 'Domaine public' },
  'Anton Chekhov with bow-tie sepia image.jpg': { auteur: 'Anonyme', licence: 'Domaine public' },
  'Victor Hugo by Étienne Carjat 1876 - full.jpg': { auteur: 'Étienne Carjat', licence: 'Domaine public' },
  'Sophocles pushkin.jpg': { auteur: "Musée Pouchkine", licence: 'Domaine public' },
  'George Sand by Nadar, 1864.jpg': { auteur: 'Nadar', licence: 'Domaine public' },
  'Paris Opera full frontal architecture, May 2009.jpg': { auteur: 'Peter Rivera', licence: 'CC BY 2.0' },
  'Epidaurus Theater.jpg': { auteur: 'Carole Raddato', licence: 'CC BY-SA 2.0' },
  'Comédie-Française.jpg': { auteur: 'Wikimedia Commons', licence: 'CC BY-SA' },
  'Shakespeare’s Globe Theatre, London.jpg': { auteur: 'Wikimedia Commons', licence: 'CC BY-SA' },
  'Avignon, Palais des Papes by JM Rosier.jpg': { auteur: 'Jean-Marc Rosier', licence: 'CC BY-SA 3.0' },
  // Grands théâtres (carte du monde)
  'Theatre of Dionysus 2017.jpg': { auteur: 'Petter Ulleland', licence: 'CC BY-SA 4.0' },
  'Interior of Teatro Olimpico (Vicenza) scena .jpg': { auteur: 'Didier Descouens', licence: 'CC BY-SA 4.0' },
  'Exterior Teatro Alla Scala high quality 01.jpg': { auteur: 'John Picken', licence: 'CC BY 2.0' },
  'Moscow-Bolshoi-Theare-1.jpg': { auteur: 'DmitriyGuryanov', licence: 'CC BY-SA 3.0' },
  'Wien - Burgtheater.JPG': { auteur: 'C.Stadler/Bwag', licence: 'CC BY-SA 4.0' },
  'New york times square-terabass.jpg': { auteur: 'Terabass', licence: 'CC BY-SA 3.0' },
  'Fachada del Teatro Colón en Buenos Aires, Argentina.jpg': { auteur: 'EEJCC', licence: 'CC0' },
  'Sydney Australia. (21339175489).jpg': { auteur: 'Bernard Spragg. NZ', licence: 'CC0' },
  'The National Theatre, South Bank, London - geograph.org.uk - 1861458.jpg': { auteur: "Anthony O'Neil", licence: 'CC BY-SA 2.0' },
  'Berlin Berliner Ensemble.jpg': { auteur: 'Wikimedia Commons', licence: 'CC BY-SA 3.0' },
  'Teatro Real de Madrid 2025.jpg': { auteur: 'Fernando', licence: 'CC BY-SA 4.0' },
  'Санкт-Петербург, Мариинский театр, фасад (edited version).jpg': { auteur: 'Nikolai Bulykin', licence: 'CC BY-SA 4.0' },
  // Festivals (carte du monde)
  'Edinburgh Fringe 037.jpg': { auteur: 'Festival Fringe Society', licence: 'CC BY-SA 3.0' },
  'Odeon of Herodes Atticus (34580450331).jpg': { auteur: 'Robert Anders', licence: 'CC BY 2.0' },
  'Panorama Belgrad.jpg': { auteur: 'Zlatan Jovanović', licence: 'CC BY 3.0' },
  'Vista de Almada by Juntas (cropped).jpg': { auteur: 'Juntas', licence: 'CC BY-SA 4.0' },
  '2020-05-23 Theater an der Wien Linke Wienzeile.jpg': { auteur: 'Rosso Robot', licence: 'CC BY-SA 4.0' },
  'Théâtre Sarah-Bernhardt 1.jpg': { auteur: 'ZeusUpsistos', licence: 'CC BY-SA 4.0' },
  'Haus der Berliner Festspiele 02-2014.jpg': { auteur: 'A.Savin', licence: 'CC BY-SA 3.0' },
  'Teatre Grec Barcelona.jpg': { auteur: 'Wikimedia Commons', licence: 'CC BY-SA 2.5' },
  'Sarajevo National Theatre.JPG': { auteur: 'Slein80', licence: 'CC BY-SA 2.0 de' },
  'The Public Theater (48072652481).jpg': { auteur: 'Ajay Suresh', licence: 'CC BY 2.0' },
  'Sammy J in the Garden of Unearthly Delights at the 2018 Adelaide Fringe Festival.jpg': { auteur: 'Linh Chameleon', licence: 'CC BY-SA 2.0' },
  'Festival Santiago a Mil 2023 - Palacio de la Moneda.jpg': { auteur: 'LuisCG11', licence: 'CC BY-SA 4.0' },
  // Encyclopédie — Histoire
  'Greek - Actor - Walters 541067.jpg': { auteur: 'Anonyme (Grèce antique)', licence: 'Domaine public' },
  'Mystery Play Metz.jpg': { auteur: 'Auguste Migette', licence: 'Domaine public' },
  'The Swan cropped.png': { auteur: 'Aernout van Buchel', licence: 'Domaine public' },
  'Pierre Mignard - Portrait de Jean-Baptiste Poquelin dit Molière (1622-1673) - Google Art Project (cropped).jpg': { auteur: 'Pierre Mignard', licence: 'Domaine public' },
  'Ariane Mnouchkine.jpg': { auteur: 'Michèle Laurent', licence: 'Attribution' },
  'Figaro-1785-title-page.jpg': { auteur: 'Anonyme', licence: 'Domaine public' },
  'André Antoine actor.jpg': { auteur: 'Charles Reutlinger', licence: 'Domaine public' },
  "Louis Léopold Boilly - L'entrée du théâtre.jpg": { auteur: 'Louis-Léopold Boilly', licence: 'Domaine public' },
  'Jean Vilar, April 1955.jpg': { auteur: 'Hans-Joachim Koch', licence: 'CC BY-SA 4.0' },
  // Encyclopédie — Mouvements
  "Portrait de Jean Racine d'après Jean-Baptiste Santerre.jpg": { auteur: "D'après Jean-Baptiste Santerre", licence: 'Domaine public' },
  'Caspar David Friedrich - Wanderer above the sea of fog.jpg': { auteur: 'Caspar David Friedrich', licence: 'Domaine public' },
  'MissJulie1906.jpg': { auteur: 'Anonyme', licence: 'Domaine public' },
  'Maurice Maeterlinck 2.jpg': { auteur: 'Anonyme', licence: 'Domaine public' },
  "En attendant Godot, Festival d'Avignon, 1978.jpeg": { auteur: 'Fernand Michaud', licence: 'CC0' },
  'Bertolt-Brecht.jpg': { auteur: 'Jörg Kolbe (Bundesarchiv)', licence: 'CC BY-SA 3.0 de' },
  'Parma-teatro-farnese-in-national-gallery.jpg': { auteur: 'bestofcinqueterre.com', licence: 'CC BY-SA 4.0' },
  'Jean-Antoine Watteau, The Italian Comedians - Getty Museum.jpg': { auteur: 'Jean-Antoine Watteau', licence: 'Domaine public' },
  'Antonin Artaud 1926.jpg': { auteur: 'Agence Meurisse', licence: 'Domaine public' },
  // Encyclopédie — Genres
  'Ny Carlsberg Glyptothek - Melpomene.jpg': { auteur: 'Wolfgang Sauber', licence: 'CC BY-SA 3.0' },
  'Tragic comic masks - roman mosaic.jpg': { auteur: 'Anonyme (mosaïque romaine)', licence: 'Domaine public' },
  'Theatre Farce (Petrov-Vodkin).jpg': { auteur: 'Kouzma Petrov-Vodkine', licence: 'Domaine public' },
  "A Doll's House.jpeg": { auteur: 'Henrik Ibsen (page de titre)', licence: 'Domaine public' },
  '3402440-Le Cid performed in Paris 1637-Burgos.jpg': { auteur: 'Gravure ancienne', licence: 'Domaine public' },
  "La puce à l'oreille, pièce de Georges Feydeau - défets de presse - btv1b525109326 (1 of 8).jpg": { auteur: 'BnF / Gallica', licence: 'Domaine public' },
  'BourgeoisGentilhomme1688.jpg': { auteur: 'Henri Wetstein (éd.)', licence: 'Domaine public' },
  'Honoré Daumier 026.jpg': { auteur: 'Honoré Daumier', licence: 'Domaine public' },
  'La Biche au bois, Alfred Choubrac.jpg': { auteur: 'Alfred Choubrac', licence: 'Domaine public' },
  'Edwin Booth Hamlet 1870.jpg': { auteur: 'J. Gurney & Son', licence: 'Domaine public' },
  // Encyclopédie — Métiers
  'David Garrick by Thomas Gainsborough.jpg': { auteur: 'Thomas Gainsborough', licence: 'Domaine public' },
  'Constantin Stanislavski.jpg': { auteur: 'Anonyme', licence: 'Domaine public' },
  'Marcel Jambon - Giuseppe Verdi - Otello Act I set design model.jpg': { auteur: 'Marcel Jambon', licence: 'Domaine public' },
  'Stage managers panel.jpg': { auteur: 'KeepOnTruckin', licence: 'CC BY 2.5' },
  'Léon Bakst - Costume Design for a Ballet (1916).jpg': { auteur: 'Léon Bakst', licence: 'Domaine public' },
  'Classical spectacular10.jpg': { auteur: 'fir0002/Flagstaffotos', licence: 'GFDL 1.2' },
  'Scenic Design by Glenn Davis, Hospital Set 2013.jpg': { auteur: 'Glenn Davis', licence: 'CC BY-SA 3.0' },
  'Apuntador (souffleur) del siglo XVIII.jpg': { auteur: 'Anonyme (XVIIIe s.)', licence: 'Domaine public' },
  'Peter Brook.JPG': { auteur: 'John Thaxter', licence: 'CC0' },
  // Costumes (galerie historique)
  'AurigaDelfi.jpg': { auteur: 'RaminusFalcon', licence: 'CC BY 3.0' },
  'Acropole Musée Athéna pensante.JPG': { auteur: 'Wikimedia Commons', licence: 'CC BY-SA 3.0' },
  'Tiberius Capri Louvre Ma1248.jpg': { auteur: 'Marie-Lan Nguyen', licence: 'Domaine public' },
  'Buskin (PSF).jpg': { auteur: 'Pearson Scott Foresman', licence: 'Domaine public' },
  '15th century costume - the Houppelande.jpg': { auteur: 'Percy Anderson', licence: 'Domaine public' },
  'Italian pourpoint.jpg': { auteur: 'Anonyme', licence: 'Domaine public' },
  'Pedro García de Benabarre St John Retable Detail.jpg': { auteur: 'Pedro García de Benabarre', licence: 'Domaine public' },
  'Voet-duque de medinacelli-prado.jpg': { auteur: 'Jacob Ferdinand Voet', licence: 'Domaine public' },
  'Mantua MET DT6543.jpg': { auteur: 'Metropolitan Museum of Art', licence: 'CC0' },
  'Robe à la Française - MET C.I.61.34a, b.jpg': { auteur: 'Metropolitan Museum of Art', licence: 'CC0' },
  'Costumes historiques Costume Louis XVI (1774), N°82, G.12342(1).jpg': { auteur: 'Achille Devéria', licence: 'CC0' },
  'Frock Coat April 1904.jpg': { auteur: 'Revue de mode (1904)', licence: 'Domaine public' },
  'Princess Dagmar of Denmark with her dog.jpg': { auteur: 'A. Hunæus', licence: 'Domaine public' },
  'Louise Brooks ggbain 32453u crop.jpg': { auteur: 'Bain News Service', licence: 'Domaine public' },
  'Livia Drusila (15708884953).jpg': { auteur: 'Ángel M. Felicísimo', licence: 'CC BY-SA 4.0' },
  'Gothic Armor MET 158414.jpg': { auteur: 'Metropolitan Museum of Art', licence: 'CC0' },
  'Young Woman with a Pink MET DT200206.jpg': { auteur: 'Hans Memling', licence: 'CC0' },
  'Heinrich Vogtherr d. J. Schalksnarr.JPG': { auteur: 'Heinrich Vogtherr le Jeune', licence: 'Domaine public' },
  'Sans-culotte.jpg': { auteur: 'Louis-Léopold Boilly', licence: 'Domaine public' },
  'Dandies of 1831.jpg': { auteur: "Caricature d'époque (1831)", licence: 'Domaine public' },
  // Personnages célèbres
  'Tartuffe Moliere.jpg': { auteur: 'Gravure ancienne', licence: 'Domaine public' },
  'Orgon verdedigt Tartuffe, RP-P-2019-3455.jpg': { auteur: 'Rijksmuseum', licence: 'CC0' },
  "Willem van Mieris - Tartuffe et Élmire supris par Damis, fils d'Orgon, lot-6325101.jpg": { auteur: 'Willem van Mieris', licence: 'Domaine public' },
  'Orgon in gesprek met Dorine, RP-P-2019-3453.jpg': { auteur: 'Rijksmuseum', licence: 'CC0' },
  // Décors (Mise en scène)
  'Chateau Versailles Galerie des Glaces.jpg': { auteur: 'Myrabella', licence: 'CC BY-SA 3.0' },
  'Rothenburg BW 4.JPG': { auteur: 'Berthold Werner', licence: 'Domaine public' },
  'Fairmead Road at High Beach, Epping Forest, Essex England.jpg': { auteur: 'Acabashi', licence: 'CC BY-SA 4.0' },
  "Autour d'une partition - Charles Baude after Albert Aublet.jpg": { auteur: "Charles Baude (d'après A. Aublet)", licence: 'Domaine public' },
  'Teniers le Jeune, Intérieur de cabaret.jpg': { auteur: 'David Teniers le Jeune', licence: 'Domaine public' },
  '0 Château de Vaux-le-Vicomte - Jardins (5).JPG': { auteur: 'Jean-Pol Grandmont', licence: 'CC BY 4.0' },
  "Vue d'Étretat.jpg": { auteur: 'Jörg Braukmann', licence: 'CC BY-SA 4.0' },
  'Coquelin ainé.jpg': { auteur: 'Anonyme (Coquelin dans Cyrano)', licence: 'Domaine public' },
  'Antigone Gives Token Burial to the Body of Her Brother Polynices MET DP807380.jpg': { auteur: 'Eugène Lenepveu', licence: 'CC0' },
  "Frontispiece to Molière's Dom Juan by P Brissart 1682 - césar.jpg": { auteur: 'Pierre Brissart / Jean Sauvé', licence: 'Domaine public' },
  'BarberSeville.jpg': { auteur: 'Anonyme', licence: 'Domaine public' },
  'Alexandre Cabanel - Phèdre.jpg': { auteur: 'Alexandre Cabanel', licence: 'Domaine public' },
  'Hamlet William Morris Hunt.jpeg': { auteur: 'William Morris Hunt', licence: 'Domaine public' },
  "Charles Dullin, L'Avare, 1944.jpg": { auteur: 'Studio Harcourt', licence: 'Domaine public' },
  'LeMisanthrope.jpg': { auteur: 'Anonyme', licence: 'Domaine public' },
  'Le Malade imaginaire.jpg': { auteur: 'Honoré Daumier', licence: 'Domaine public' },
  'Les Fourberies de Scapin frontispice.jpg': { auteur: 'Pierre Brissart', licence: 'Domaine public' },
  "L'EcoledesFemmes.jpg": { auteur: 'T. de Marc.', licence: 'Domaine public' },
  '1868, Mugeres célebres de España y Portugal, Gimena mujer del Cid, AB195 0363 (cropped).jpg': { auteur: 'Université de Séville', licence: 'Domaine public' },
  'Racine - Britannicus, Barbin, 1670, 2.jpg': { auteur: 'Jean Racine (éd. 1670)', licence: 'CC0' },
  'Andromaque 1668 title page.JPG': { auteur: 'Racine (éd. 1668)', licence: 'Domaine public' },
  'Jacques-Louis David- Andromache Mourning Hector.JPG': { auteur: 'Jacques-Louis David', licence: 'Domaine public' },
  'Alfons Mucha - 1896 - Lorenzaccio.jpg': { auteur: 'Alphonse Mucha', licence: 'Domaine public' },
  "Musset - On ne badine pas avec l'amour, 1884.djvu": { auteur: 'Alfred de Musset (éd. 1884)', licence: 'Domaine public' },
  'Romeo and juliet brown.jpg': { auteur: 'Ford Madox Brown', licence: 'Domaine public' },
  'Frank Bernard Dicksee - Romeo and Juliet, 1884.jpg': { auteur: 'Frank Bernard Dicksee', licence: 'Domaine public' },
  'Orson Welles as Macbeth.jpg': { auteur: 'Republic Pictures (1948)', licence: 'Domaine public' },
  'Ellen Terry as Lady Macbeth.jpg': { auteur: 'John Singer Sargent', licence: 'Domaine public' },
  'Oedipus and Sphinx, pelike, 450-440 BC, Berlin F 2355, 141646.jpg': { auteur: 'Zde (photo, vase antique)', licence: 'CC BY-SA 4.0' },
  'Roybet, Ferdinand - Don César de Bazan - 195 - Maison de Victor Hugo.jpg': { auteur: 'Ferdinand Roybet', licence: 'Domaine public' },
  'Hernani Act I - Sc. III. by Paris & Martin after Vierge.png': { auteur: "A. Paris & C. Martin (d'après Vierge)", licence: 'Domaine public' },
  'Le Baiser de Roxane, stances, tirées de la scène du Balcon, troisième acte de "Cyrano de Bergerac". Paroles de Edmond Rostand. Chant et piano - bpt6k393485g (1 of 6).jpg': { auteur: 'BnF / Gallica', licence: 'Domaine public' },
  'Molière as Sganarelle.jpg': { auteur: 'Claude Simonin', licence: 'Domaine public' },
  'Cinna corneille.jpg': { auteur: 'Corneille (éd. ancienne)', licence: 'Domaine public' },
  'Berenice 1671 title page.JPG': { auteur: 'Racine (éd. 1671)', licence: 'Domaine public' },
  'Beaumarchais Le mariage de Figaro Ruault Paris 1785 Titel.jpg': { auteur: 'Anonyme (éd. 1785)', licence: 'Domaine public' },
  'Ramberg figaro 1.jpg': { auteur: 'Johann Heinrich Ramberg', licence: 'Domaine public' },
  'Le Bourgeois Gentilhomme, Molière, couverture.png': { auteur: 'Édition ancienne (Molière)', licence: 'Domaine public' },
  'LesFemmesSavantes.jpg': { auteur: 'Gravure ancienne', licence: 'Domaine public' },
  'John William Waterhouse - Ophelia (1894).jpg': { auteur: 'John William Waterhouse', licence: 'Domaine public' },
  "Umberto Brunelleschi, illustration pour Fantasio d'Alfred de Musset.jpg": { auteur: 'Umberto Brunelleschi', licence: 'Domaine public' },
  'MarivauxGameLoveChance.jpg': { auteur: 'Bertall', licence: 'Domaine public' },
  'SAND Maurice Masques et bouffons 01.jpg': { auteur: 'Maurice Sand', licence: 'Domaine public' },
  'Médée furieuse - Eugène Delacroix - Musée du Louvre Peintures RF 1402.jpg': { auteur: 'Eugène Delacroix', licence: 'Domaine public' },
  'Nazimova 1907.jpg': { auteur: 'Sigismund Ivanowski', licence: 'Domaine public' },
  'Programme for the première of Ubu Roi.jpg': { auteur: 'Alfred Jarry (programme, 1896)', licence: 'Domaine public' },
  // Auteurs contemporains (ajout 2026)
  'Alexis Michalik - Molières 2018 9.jpg': { auteur: 'Georges Biard', licence: 'CC BY-SA 4.0' },
  'Eric-Emmanuel Schmitt 2013.jpg': { auteur: 'Georges Biard', licence: 'CC BY-SA 3.0' },
  'Olivier py (cropped).jpg': { auteur: 'Emile Zeizig', licence: 'CC BY-SA 3.0' },
  'Jean-Claude Grumberg par Claude Truong-Ngoc novembre 2013.jpg': { auteur: 'Claude Truong-Ngoc', licence: 'CC BY-SA 3.0' },
  "Pauline Peyrade (born 1986) in the video 'Pauline Peyrade - Les habitantes'.png": { auteur: 'Librairie Mollat', licence: 'CC BY 4.0' },
  'Nathalie Papin.jpg': { auteur: 'Quantik53', licence: 'Domaine public' },
  'Festival des Vieilles Charrues 2017 - Kery James - 085.jpg': { auteur: 'Thesupermat', licence: 'CC BY-SA 4.0' },
  'Noelle Renaude.jpg': { auteur: 'Noëlle Renaude', licence: 'CC BY-SA 4.0' },
  'Autoportrait EC-2.jpg': { auteur: 'Enzo Cormann', licence: 'CC BY-SA 4.0' },
  'Portrait sur fond blanc.jpg': { auteur: 'Libre entre les lignes', licence: 'CC BY-SA 4.0' },
  'Carole Fréchette.JPG': { auteur: 'Chronos137', licence: 'CC BY-SA 3.0' },
  'Portrait de Serge Valletti, Marseille 2019.jpg': { auteur: 'Richard Patatut', licence: 'CC BY-SA 4.0' },
  'Lecture-scenique-iphigenie_jr-lemoine.jpg': { auteur: 'bdesir', licence: 'CC BY-SA 4.0' },
  // Auteurs contemporains
  'Lagarce.jpg': { auteur: 'Babelio', licence: 'CC BY-SA 4.0' },
  'Yasmina Reza at XIII Prix Diálogo - Ceremonia de entrega.jpg': { auteur: 'power axle', licence: 'CC BY 2.0' },
  'Joël Pommerat.jpg': { auteur: 'David Balicki', licence: 'CC BY-SA 4.0' },
  'OscarsCoulisses2021.jpg': { auteur: 'StradellaLand', licence: 'CC0' },
  'Valère Novarina - portrait de Fernand Michaud - btv1b103296260.jpg': { auteur: 'Fernand Michaud', licence: 'Domaine public' },
  'Michel Vinaver - 2006.jpg': { auteur: 'Wikinade', licence: 'CC BY-SA 4.0' },
  'Marie Ndiaye 01.jpg': { auteur: 'Bengt Oberger', licence: 'CC BY-SA 4.0' },
  'Fabrice Melquiot.jpg': { auteur: 'Unmecmoi', licence: 'CC BY-SA 4.0' },
  // Portraits des grands dramaturges (ajout)
  'Pierre Carlet de Chamblain de Marivaux - Versailles MV 2985.jpg': { auteur: 'D\'après Louis-Michel van Loo', licence: 'Domaine public' },
  'Landelle, Charles - Alfred de Musset - Musée d\'Orsay.png': { auteur: 'Charles Landelle', licence: 'Domaine public' },
  'Atelier de Nicolas de Largillière, portrait de Voltaire, détail (musée Carnavalet) -002.jpg': { auteur: 'Atelier de Nicolas de Largillière', licence: 'Domaine public' },
  'G Feydeau Carolus-Duran Lille 2918.jpg': { auteur: 'D\'après Carolus-Duran', licence: 'Domaine public' },
  'Félix Nadar 1820-1910 portraits Eugène Labiche.jpg': { auteur: 'Nadar', licence: 'Domaine public' },
  'Georges Courteline circa 1890.jpg': { auteur: 'Anonyme', licence: 'Domaine public' },
  'Schaarwächter Henrik Ibsen cropped.jpg': { auteur: 'J. C. Schaarwächter', licence: 'Domaine public' },
  'Edmond Rostand en habit vert 01.jpg': { auteur: 'Léopold-Émile Reutlinger', licence: 'Domaine public' },
  'Nadar - Alexander Dumas père (1802-1870) - Google Art Project 2.jpg': { auteur: 'Nadar (Google Art Project)', licence: 'Domaine public' },
  'Alfred Jarry.jpg': { auteur: 'Atelier Nadar', licence: 'Domaine public' },
  '奥·巴尔扎克.png': { auteur: 'Louis-Auguste Bisson', licence: 'Domaine public' },
  'Alessandro Longhi - Ritratto di Carlo Goldoni (c 1757) Ca Goldoni Venezia - Close-up.jpg': { auteur: 'Alessandro Longhi (photo D. Descouens)', licence: 'CC BY-SA 4.0' },
  'Alain-René Lesage.png': { auteur: 'Anonyme', licence: 'Domaine public' },
  'Denis Diderot 111.PNG': { auteur: 'Anonyme', licence: 'Domaine public' },
  'Maupassant par Nadar.jpg': { auteur: 'Nadar', licence: 'Domaine public' },
  'Émile Augier by Adam-Salomon c1870s.jpg': { auteur: 'Antoine Samuel Adam-Salomon', licence: 'Domaine public' },
  'Jean de La Fontaine.PNG': { auteur: 'Hyacinthe Rigaud', licence: 'Domaine public' },
  'Aristofanes.jpg': { auteur: 'Buste antique, via Wikimedia Commons', licence: 'Domaine public' },
  'Euripide.jpg': { auteur: 'Buste antique, via Wikimedia Commons', licence: 'CC BY-SA 4.0' },
  'Oscar Wilde (1854-1900) 1889, May 23. Picture by W. and D. Downey.jpg': { auteur: 'W. & D. Downey', licence: 'Domaine public' },
};

export function creditFor(file?: string): Credit | undefined {
  if (!file) return undefined;
  return CREDITS[file];
}
